function sps = assemble_afgrid(filenames, reynolds, delta)
% sps = assemble_afgrid(filenames, reynolds, delta)
%
% Produce a struct which contains data suitable for interpolation of
% airfoil normal force, drag and pitch moment as a function of effective
% angle of attack, Reynolds number and flap deflection.
%
% sps : interpolation data to be passed to eval_afgrid
% filenames : an (m-by-n) cell array with filenames containing alpha polars
%             generated by XFoil for a fixed delta and Reynolds number.
%             rows : Reynolds number, columns: flap deflections
% reynolds : the Reynolds numbers fow which the polars were computed, there
%            must be at least 2 Reynolds numbers
% delta    : Flap deflections - leave this out if only one flap deflection 
%            is available
    
    if nargin < 3
        delta = 0;
    end

    if size(filenames, 1) ~= numel(reynolds)
        error('Must provide one row of files for each Reynolds number');
    end
    
    if size(filenames, 2) ~= numel(delta)
        error('Must provide one column of files for each flap deflection');
    end
    
    nd = numel(delta);
    [sdelta, jdx] = sort(delta);
    sps.delta = sdelta;
    
    nr = numel(reynolds);
    lgr = 6^2.58 * (log10(reynolds) .^ (-2.58));
    [sre, idx] = sort(lgr);
    sps.logre = sre;
    
    na = 361;
    aip = pi/180 * linspace(-45, 45, na)';
    sps.alphamin = aip(1);
    sps.alphamax = aip(end);
    
    if nd > 1
        
        gcz = zeros(na, nr, nd);
        gcd = zeros(na, nr, nd);
        gcm = zeros(na, nr, nd);
        gcza = zeros(na, nr, nd);
        
        for kj = 1:nd
            for ki = 1:nr
                [alpha, CL, CD, CM] = import_xfoil_polar(filenames{idx(ki), jdx(kj)});
                CZ = CL.*cos(alpha) + CD.*sin(alpha);
                if is_octave
                  spl = splinefit(alpha, [CZ, CD, CM]', 8);
                else
                  spl = spap2(8, 4, alpha, [CZ, CD, CM]');
                end 
                [gcz(:,ki,kj), gcd(:,ki,kj), gcm(:,ki,kj), gcza(:,ki,kj)] = blendplate(spl, aip);
            end
        end
        
        if is_octave
          sps.aip = aip;
          sps.gcz = gcz;
          sps.gcd = gcd;
          sps.gcm = gcm;
          sps.gcza = gcza;
        else
          sps.ipcz = griddedInterpolant({aip, sps.logre, sps.delta}, gcz, ...
              'spline', 'linear');
          sps.ipcd = griddedInterpolant({aip, sps.logre, sps.delta}, gcd, ...
              'spline', 'linear');
          sps.ipcm = griddedInterpolant({aip, sps.logre, sps.delta}, gcm, ...
              'spline', 'linear');
          sps.ipcza = griddedInterpolant({aip, sps.logre, sps.delta}, gcza, ...
              'spline', 'linear');
        end
        
    else
        
        gcz = zeros(na, nr);
        gcd = zeros(na, nr);
        gcm = zeros(na, nr); 
        gcza = zeros(na, nr);

        for ki = 1:nr
            [alpha, CL, CD, CM] = import_xfoil_polar(filenames{idx(ki)});
            CZ = CL.*cos(alpha) + CD.*sin(alpha);
            if is_octave
              spl = splinefit(alpha, [CZ, CD, CM]', 8);
            else
              spl = spap2(8, 4, alpha, [CZ, CD, CM]');
            end
            [gcz(:,ki), gcd(:,ki), gcm(:,ki), gcza(:,ki)] = blendplate(spl, aip);
        end
        
        if is_octave
          sps.aip = aip;
          sps.gcz = gcz;
          sps.gcd = gcd;
          sps.gcm = gcm;
          sps.gcza = gcza;
        else
          sps.ipcz = griddedInterpolant({aip, sps.logre}, gcz, ...
              'spline', 'linear');
          sps.ipcd = griddedInterpolant({aip, sps.logre}, gcd, ...
              'spline', 'linear');
          sps.ipcm = griddedInterpolant({aip, sps.logre}, gcm, ...
              'spline', 'linear');
          sps.ipcza = griddedInterpolant({aip, sps.logre}, gcza, ...
              'spline', 'linear');
        end
        
    end
    
    
end