function [r,J] = residual(acg, fs, Gamma)
% [r,J] = residual(acg, fs, Gamma)
%
% Determine the mismatch between normal force according to Kutta-Joukowski
% theorem and the forces generated by the sections at the present downwash
% due to current spanwise lift distribution.
%
% r   : residual vector 
% J   : Jacobian, dr/dGamma
% acg : aircraft geometry (struct)
% fs  : flight condition (struct)
% Gamma : Current value (or initial guess) of vortex strengths 

    dojac = 0;
    if nargout > 1
      dojac = 1;
    end 

    % force coefficients for each segment and total velocity 
    % (freestream + induced) from lifting-line solution using Gamma
    if dojac
      [cxyz, vt, Jcz, Jvz] = segment_coefficients(acg, fs, Gamma);
    else 
      [cxyz, vt] = segment_coefficients(acg, fs, Gamma);
    end
    
    % compute local AoA and Reynolds numbers based on total velocities
    
    % alpha = acg.incidence + atan2(vt(:,3), vt(:,1));
    [localpha, vax, vup] = vortex_alpha(acg, vt);
    uc = sqrt(sum( vt.^2, 2 ));
    Re = uc .* acg.chord ./ fs.nu;
    
    % query the airfoil Cz-alpha curve : call the airfoil lookup function 
    % acg.foil and pass the current AoA and Reynolds number, use only the
    % local 2D normal force coefficients
    if dojac 
      [Czf, Cd, Cm, Cza] = feval(acg.foil, acg, fs, localpha, Re);
    else 
      [Czf, Cd, Cm] = feval(acg.foil, acg, fs, localpha, Re);
    end 
    
    % coefficient in the local up direction 
    cup = sum(acg.zup .* cxyz, 2); 
    
    % r is a zero vector (or almost) when the Kutta-Joukowski lift from 
    % Gamma(y) matches the local airfoil lift generated at the induced
    % angles of attack produced by Gamma(y)
    r = cup - Czf;
    
    % Jacobian matrix is dr/dGamma at fs 
    % Cz = Cz(alpha) 
    % dCz/dGamma = dCz/dalpha * dalpha/dGamma
    % dalpha/dGamma = 1/vx * ( dvz/dGamma ), to first order 
    % dCz/dGamma = Cza/vx * dvz/dGamma
    if dojac
      J = Jcz - diag(Cza ./ vax) *  Jvz;
    end 
    
end  